#!/usr/bin/env python3
"""Bake a small, deterministic runtime table from an official USGS DEM query.

The checked-in PNG is the portable source artifact.  The generated JS table is
used by the synchronous backdrop constructor so the renderer never fetches a
DEM at runtime.  Pillow is intentionally the only dependency; the source can
be fetched with curl from the URL recorded in the provenance document.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image


SOURCE_URL = (
    "https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/"
    "ImageServer/exportImage?bbox=-121.35,48.715,-121.25,48.785&size=128,128&"
    "format=tiff&pixelType=F32&bboxSR=4326&imageSR=4326&f=image"
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="USGS exportImage GeoTIFF")
    parser.add_argument("--png", type=Path, required=True)
    parser.add_argument("--module", type=Path, required=True)
    args = parser.parse_args()

    source_bytes = args.source.read_bytes()
    source_sha256 = hashlib.sha256(source_bytes).hexdigest()
    values = np.asarray(Image.open(args.source), dtype=np.float32)
    if values.ndim != 2 or values.shape[0] < 2 or values.shape[1] < 2:
        raise SystemExit("expected a 2D DEM with at least 2x2 samples")
    if not np.isfinite(values).all():
        raise SystemExit("DEM contains non-finite samples")

    height, width = values.shape
    minimum = float(values.min())
    maximum = float(values.max())
    if maximum <= minimum:
        raise SystemExit("DEM has no relief")
    quantized = np.rint((values - minimum) / (maximum - minimum) * 65535.0)
    quantized = np.clip(quantized, 0, 65535).astype(np.uint16)
    args.png.parent.mkdir(parents=True, exist_ok=True)
    args.module.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(quantized, mode="I;16").save(args.png, format="PNG", optimize=True)
    png_sha256 = hashlib.sha256(args.png.read_bytes()).hexdigest()

    flat = ",".join(str(int(v)) for v in quantized.ravel())
    module = f'''// Generated by scripts/build_backdrop_dem.py; do not hand edit.
export const NORTH_CASCADES_DEM = Object.freeze({{
  width: {width}, height: {height},
  minElevation: {minimum:.7f}, maxElevation: {maximum:.7f},
  values: Uint16Array.from([{flat}]),
}});
'''
    # Keep the generated module readable and avoid an accidental source fetch in
    # the app.  The PNG remains the human-auditable offline height asset.
    args.module.write_text(module)

    metadata = {
        "source": SOURCE_URL,
        "source_sha256": source_sha256,
        "asset_sha256": png_sha256,
        "width": width,
        "height": height,
        "min_elevation_m": minimum,
        "max_elevation_m": maximum,
    }
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
